version: '3'
services:
  web:
    image: dshot/docker-httpd-tomcat_web
    deploy:
      # mode: global
      replicas: 3
      resources:
        limits:
          cpus: "0.2"
          memory: 150M
      restart_policy:
        condition: on-failure
    expose:
      - "8009"
    networks:
      - web_net
    build: tomcat/.
  httpd:
    image: dshot/docker-httpd-tomcat_httpd
    ports:
      - 80
    build: httpd/.
    networks:
      - web_net
networks:
  web_net:

