version: '3'
services:
  web:
    image: 127.0.0.1:5000/docker-httpd-tomcat_web
    deploy:
      # mode: global
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    # expose:
    #   - "8009"
    build: tomcat/.
  httpd:
    image: 127.0.0.1:5000/docker-httpd-tomcat_httpd
    volumes:
      - ./logs:/var/log/apache2
    ports:
      - 80
    build: httpd/.

